# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartTimePayroll',
            new_name='PermanentPayroll',
        ),
        migrations.RenameModel(
            old_name='FullTimePayroll',
            new_name='TemporaryPayroll',
        ),
    ]
