# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170614_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
