# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_prospect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
