SECRET_KEY = '%(SECRET_KEY)s'

GITHUB_USER = '%(GITHUB_USER)s'
GITHUB_PASS = '%(GITHUB_PASS)s'

SENTRY_DSN = '%(SENTRY_DSN)s'

STRIPE_API_SECRET_KEY = '%(STRIPE_API_SECRET_KEY)s'
STRIPE_API_PUBLISHABLE_KEY = '%(STRIPE_API_PUBLISHABLE_KEY)s'
