# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20160421_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_invoiceable',
            field=models.BooleanField(default=True),
        ),
    ]
