# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_order_set_invoicable_false'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_item',
            new_name='invoiceitem_id',
        ),
    ]
