# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField()),
                ('organization_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('contract_state', models.CharField(choices=[(b'ACTIVE', b'active'), (b'COMPLETE', b'complete')], max_length=8)),
                ('contract_type', models.CharField(choices=[(b'HOURLY', b'hourly'), (b'FIXED', b'fixed')], max_length=8)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField()),
                ('number_of_months', models.IntegerField()),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('reconciled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('projected_values', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actual_values', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fiscal_year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.FiscalYear')),
            ],
        ),
        migrations.CreateModel(
            name='PartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_type', models.CharField(choices=[(b'NON_STUDENT', b'non student'), (b'STUDENT', b'student')], max_length=12)),
                ('hourly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('hours_work', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[(b'SPA', b'SPA'), (b'EPA', b'EPA')], max_length=3)),
                ('social_security_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fed_health_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('retirement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('medical_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('staff_benefits_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fringe_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('name', models.CharField(max_length=50)),
                ('data_payable', models.DateField()),
                ('date_payed', models.DateField()),
                ('reoccuring', models.IntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Month')),
            ],
            bases=('accounting.lineitem',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('transation_state', models.CharField(choices=[(b'NOT_INVOICED', b'not invoiced'), (b'RECIEVED', b'recieved'), (b'INVOICED', b'invoiced')], max_length=15)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Month')),
            ],
            bases=('accounting.lineitem',),
        ),
    ]
