# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('account_number', models.CharField(max_length=12)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=b'CSC', max_length=4)),
                ('contract_number', models.IntegerField()),
                ('organization_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('contract_state', models.CharField(choices=[(b'ACTIVE', b'active'), (b'COMPLETE', b'complete')], max_length=8)),
                ('contract_type', models.CharField(choices=[(b'HOURLY', b'hourly'), (b'FIXED', b'fixed')], max_length=8)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('reconciled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('projected_values', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actual_values', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fiscal_year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.FiscalYear')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('accounting.lineitem',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('name', models.CharField(max_length=50)),
                ('date_payable', models.DateField()),
                ('date_payed', models.DateField(default=None, null=True)),
            ],
            bases=('accounting.lineitem',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('name', models.CharField(max_length=50)),
                ('date_payable', models.DateField()),
                ('date_payed', models.DateField(default=None, null=True)),
            ],
            bases=('accounting.lineitem',),
        ),
        migrations.CreateModel(
            name='PartTime',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Personnel')),
                ('hourly_type', models.CharField(choices=[(b'NON_STUDENT', b'non student'), (b'STUDENT', b'student')], max_length=12)),
                ('hourly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('hours_work', models.IntegerField()),
            ],
            bases=('accounting.personnel',),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Personnel')),
                ('salary_type', models.CharField(choices=[(b'SPA', b'SPA'), (b'EPA', b'EPA')], max_length=3)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('social_security_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fed_health_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('retirement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('medical_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('staff_benefits_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fringe_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            bases=('accounting.personnel',),
        ),
        migrations.AddField(
            model_name='personnel',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Month'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Income')),
                ('number', models.IntegerField()),
                ('transition_state', models.CharField(choices=[(b'NOT_INVOICED', b'not invoiced'), (b'RECIEVED', b'recieved'), (b'INVOICED', b'invoiced')], max_length=15)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract')),
            ],
            bases=('accounting.income',),
        ),
        migrations.AddField(
            model_name='payroll',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Expense'),
        ),
    ]
