# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='month',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='month',
            field=models.ForeignKey(default=2014, on_delete=django.db.models.deletion.CASCADE, to='accounting.Month'),
            preserve_default=False,
        ),
    ]
