# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='business_unit',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Cash'),
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
    ]
