# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='account_number',
            field=models.CharField(max_length=12, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='date_associated',
            field=models.DateField(verbose_name='Date Associated'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='Reconciled'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], max_length=8, verbose_name='Contract State'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('HOURLY', 'Hourly')], max_length=8, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.CharField(default='CSC', max_length=4, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Contract Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date Paid'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_payable',
            field=models.DateField(verbose_name='Date Payable'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PAYROLL', 'Payroll')], max_length=7, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='Reconciled'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='employee_id',
            field=models.IntegerField(verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='fed_health_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Federal Health Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='fringe_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Fringe Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='medical_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Medical Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='retirement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Retirement Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='salary_type',
            field=models.CharField(choices=[('EPA', 'EPA'), ('SPA', 'SPA')], max_length=3, verbose_name='Salary Type'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='social_security_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Social Security Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='staff_benefits_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Staff Benefits Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date Paid'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_payable',
            field=models.DateField(verbose_name='Date Payable'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='income',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='Reconciled'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transition_state',
            field=models.CharField(choices=[('INVOICED', 'Invoiced'), ('NOT_INVOICED', 'Not Invoiced'), ('RECEIVED', 'Received')], max_length=15, verbose_name='Transition State'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='employee_id',
            field=models.IntegerField(verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='hourly_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Hourly Amount'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='hourly_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('NON_STUDENT', 'Non-Student')], max_length=12, verbose_name='Hourly Type'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='hours_work',
            field=models.IntegerField(verbose_name='Hours Worked'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('VIEWER', 'Viewer')], max_length=12, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
