# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20160210_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='fiscal_year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.FiscalYear'),
        ),
    ]
