# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170201_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='fed_health_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Federal Health Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='fringe_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fringe Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='medical_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='retirement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retirement Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='social_security_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Social Security Amount'),
        ),
        migrations.AlterField(
            model_name='fulltime',
            name='staff_benefits_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Staff Benefits Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Actual Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Predicted Amount'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='hourly_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hourly Amount'),
        ),
    ]
