# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinguser',
            name='business_unit',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
            preserve_default=False,
        ),
    ]
