# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20161024_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[(b'PAYROLL', b'Payroll'), (b'GENERAL', b'General')], default='GENERAL', max_length=7, verbose_name=b'Expense Type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
