# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_month_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
