# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:21
from __future__ import unicode_literals

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20170619_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('est_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[accounting.models.validate_positive])),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[accounting.models.validate_positive])),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit')),
            ],
        ),
    ]
