# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountinguser_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinguser',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
    ]
