# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20160830_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinguser',
            name='permission',
            field=models.CharField(choices=[(b'VIEWER', b'viewer'), (b'MANAGER', b'manager')], max_length=12),
        ),
    ]
