# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_lineitem_reconciled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Expense_amount',
            new_name='amount',
        ),
    ]
