# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_prospects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prospects',
            new_name='Prospect',
        ),
    ]
