# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20170622_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='name',
            field=models.CharField(default='Prospect #%d % (self.id)', max_length=255, verbose_name='Name'),
        ),
    ]
