# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20160830_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='user',
        ),
    ]
