# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20160218_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
    ]
