# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20160225_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract'),
            preserve_default=False,
        ),
    ]
