# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_businessunit_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountinguser',
            unique_together=set([('user', 'business_unit', 'permission')]),
        ),
    ]
