# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 17:58
from __future__ import unicode_literals

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20170626_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='probability',
            field=models.FloatField(default=0, validators=[accounting.models.validate_positive, accounting.models.validate_percentile]),
        ),
    ]
