# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20160907_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountingUser',
            new_name='UserTeamRole',
        ),
        migrations.RenameField(
            model_name='userteamrole',
            old_name='permission',
            new_name='role',
        ),
        migrations.AlterUniqueTogether(
            name='userteamrole',
            unique_together=set([('user', 'business_unit', 'role')]),
        ),
    ]
