# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20160226_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='business_unit',
        ),
    ]
