# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20160909_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userteamrole',
            unique_together=set([('user', 'business_unit')]),
        ),
    ]
