# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_lineitem_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='business_unit',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit'),
        ),
    ]
