# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20160913_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date_payed',
        ),
        migrations.AddField(
            model_name='income',
            name='date_paid',
            field=models.DateField(default=None, null=True, verbose_name=b'Date Paid'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_state',
            field=models.CharField(choices=[(b'ACTIVE', b'Active'), (b'COMPLETE', b'Complete')], max_length=8, verbose_name=b'Contract State'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[(b'HOURLY', b'Hourly'), (b'FIXED', b'Fixed')], max_length=8, verbose_name=b'Contract Type'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name=b'Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transition_state',
            field=models.CharField(choices=[(b'NOT_INVOICED', b'Not Invoiced'), (b'RECIEVED', b'Recieved'), (b'INVOICED', b'Invoiced')], max_length=15, verbose_name=b'Transition State'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='hourly_type',
            field=models.CharField(choices=[(b'NON_STUDENT', b'Non-Student'), (b'STUDENT', b'Student')], max_length=12, verbose_name=b'Hourly Type'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fed_health_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Federal Health Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='retirement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Retirement Amount'),
        ),
    ]
