# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20160926_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name=b'Contract Name'),
        ),
    ]
