# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20160226_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reoccuring',
        ),
    ]
