# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_expense_reoccuring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.LineItem')),
                ('name', models.CharField(max_length=50)),
                ('data_payable', models.DateField()),
                ('date_payed', models.DateField(default=None, null=True)),
            ],
            bases=('accounting.lineitem',),
        ),
    ]
