# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20160926_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transition_state',
            field=models.CharField(choices=[(b'NOT_INVOICED', b'Not Invoiced'), (b'RECEIVED', b'Received'), (b'INVOICED', b'Invoiced')], max_length=15, verbose_name=b'Transition State'),
        ),
    ]
