# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_income'),
    ]

    operations = [
        migrations.DeleteModel(name= 'Invoice'),
    ]
