# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20160927_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary',
            new_name='FullTime',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='month',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='date_for',
            field=models.DateField(default=None, verbose_name=b'Date For'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='date_for',
            field=models.DateField(default=None, verbose_name=b'Date For'),
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
