# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Cash = apps.get_model("accounting", "Cash")
    Expense = apps.get_model("accounting", "Expense")
    Income = apps.get_model("accounting", "Income")
    Invoice = apps.get_model("accounting", "Invoice")
    FullTime = apps.get_model("accounting", "FullTime")
    PartTime = apps.get_model("accounting", "PartTime")
    Payroll = apps.get_model("accounting", "Payroll")

    for obj in Cash.objects.using(db_alias).all():
        CashPH.objects.create(
            pk = obj.pk, 
            business_unit = obj.business_unit,
            predicted_amount = obj.predicted_amount,
            actual_amount = obj.actual_amount,
            reconciled = obj.reconciled,
            name = obj.name,
        )

    for obj in Expense.objects.using(db_alias).all():
        ExpensePH.objects.create(
            pk = obj.pk, 
            business_unit = obj.business_unit,
            predicted_amount = obj.predicted_amount,
            actual_amount = obj.actual_amount,
            reconciled = obj.reconciled,
            name = obj.name,
            date_payable = obj.date_payable,
            date_paid = obj.date_paid
        )

    for obj in Income.objects.using(db_alias).all():
        IncomePH.objects.create(
            pk = obj.pk, 
            business_unit = obj.business_unit,
            predicted_amount = obj.predicted_amount,
            actual_amount = obj.actual_amount,
            reconciled = obj.reconciled,
            name = obj.name,
            date_payable = obj.date_payable,
            date_paid = obj.date_paid
        )

    for obj in Invoice.objects.using(db_alias).all():
        InvoicePH.objects.create(
            pk = obj.pk, 
            contract = obj.contract,
            number = obj.number,
            transition_state = obj.transition_state,
        )

    for obj in FullTime.objects.using(db_alias).all():
        FullTimePH.objects.create(
            pk = obj.pk, 
            business_unit = obj.business_unit.pk,
            first_name = obj.first_name,
            last_name = obj.last_name,
            position = obj.position,
            salary_type = obj.salary_type,
            salary_amount = obj.salary_amount,
            social_security_amount = obj.social_security_amount,
            fed_health_insurance_amount = obj.fed_health_insurance_amount,
            retirement_amount = obj.retirement_amount,
            medical_insurance_amount = obj.medical_insurance_amount,
            staff_benefits_amount = obj.staff_benefits_amount,
            fringe_amount = obj.fringe_amount,
        )

    for obj in PartTime.objects.using(db_alias).all():
        PartTimePH.objects.create(
            pk = obj.pk,
            business_unit = obj.business_unit.pk,
            first_name = obj.first_name,
            last_name = obj.last_name,
            position = obj.position,
            hourly_type = obj.hourly_type,
            hourly_amount = obj.hourly_amount,
            hours_work = obj.hours_work,
        )

    for obj in Payroll.objects.using(db_alias).all():
        PayrollPH.objects.create(
            pk = obj.pk,
            expense = obj.expense.pk,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20160927_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('date_payable', models.DateField(verbose_name=b'Date Payable')),
                ('date_paid', models.DateField(blank=True, default=None, null=True, verbose_name=b'Date Paid')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullTimePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Last Name')),
                ('employee_id', models.IntegerField(verbose_name=b'Employee ID')),
                ('position', models.CharField(max_length=50, verbose_name=b'Position')),
                ('salary_type', models.CharField(choices=[(b'SPA', b'SPA'), (b'EPA', b'EPA')], max_length=3, verbose_name=b'Salary Type')),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Salary')),
                ('social_security_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Social Security Amount')),
                ('fed_health_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Federal Health Insurance Amount')),
                ('retirement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Retirement Amount')),
                ('medical_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Medical Insurance Amount')),
                ('staff_benefits_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Staff Benefits Amount')),
                ('fringe_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Fringe Amount')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('date_payable', models.DateField(verbose_name=b'Date Payable')),
                ('date_paid', models.DateField(blank=True, default=None, null=True, verbose_name=b'Date Paid')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('number', models.IntegerField(verbose_name=b'Number')),
                ('transition_state', models.CharField(choices=[(b'NOT_INVOICED', b'Not Invoiced'), (b'RECEIVED', b'Received'), (b'INVOICED', b'Invoiced')], max_length=15, verbose_name=b'Transition State')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract', verbose_name=b'Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartTimePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Last Name')),
                ('employee_id', models.IntegerField(verbose_name=b'Employee ID')),
                ('position', models.CharField(max_length=50, verbose_name=b'Position')),
                ('hourly_type', models.CharField(choices=[(b'NON_STUDENT', b'Non-Student'), (b'STUDENT', b'Student')], max_length=12, verbose_name=b'Hourly Type')),
                ('hourly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Hourly Amount')),
                ('hours_work', models.IntegerField(verbose_name=b'Hours Worked')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpensePH', verbose_name=b'Expense')),
            ],
        ),
        migrations.RenameModel(
            old_name='Salary',
            new_name='FullTime',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='month',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='role',
            field=models.CharField(choices=[(b'VIEWER', b'Viewer'), (b'MANAGER', b'Manager')], max_length=12, verbose_name=b'Role'),
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.RunPython(forwards_func),
    ]
