# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20160927_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('date_payable', models.DateField(verbose_name=b'Date Payable')),
                ('date_paid', models.DateField(blank=True, default=None, null=True, verbose_name=b'Date Paid')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullTimePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Last Name')),
                ('employee_id', models.IntegerField(verbose_name=b'Employee ID')),
                ('position', models.CharField(max_length=50, verbose_name=b'Position')),
                ('salary_type', models.CharField(choices=[(b'SPA', b'SPA'), (b'EPA', b'EPA')], max_length=3, verbose_name=b'Salary Type')),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Salary')),
                ('social_security_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Social Security Amount')),
                ('fed_health_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Federal Health Insurance Amount')),
                ('retirement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Retirement Amount')),
                ('medical_insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Medical Insurance Amount')),
                ('staff_benefits_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Staff Benefits Amount')),
                ('fringe_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Fringe Amount')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Predicted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Actual Amount')),
                ('reconciled', models.BooleanField(default=False, verbose_name=b'Reconciled')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('date_payable', models.DateField(verbose_name=b'Date Payable')),
                ('date_paid', models.DateField(blank=True, default=None, null=True, verbose_name=b'Date Paid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartTimePH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Last Name')),
                ('employee_id', models.IntegerField(verbose_name=b'Employee ID')),
                ('position', models.CharField(max_length=50, verbose_name=b'Position')),
                ('hourly_type', models.CharField(choices=[(b'NON_STUDENT', b'Non-Student'), (b'STUDENT', b'Student')], max_length=12, verbose_name=b'Hourly Type')),
                ('hourly_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Hourly Amount')),
                ('hours_work', models.IntegerField(verbose_name=b'Hours Worked')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpensePH', verbose_name=b'Expense')),
            ],
        ),
        migrations.RenameModel(
            old_name='Salary',
            new_name='FullTime',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='month',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='role',
            field=models.CharField(choices=[(b'VIEWER', b'Viewer'), (b'MANAGER', b'Manager')], max_length=12, verbose_name=b'Role'),
        ),
        migrations.CreateModel(
            name='InvoicePH',
            fields=[
                ('incomeph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.IncomePH')),
                ('number', models.IntegerField(verbose_name=b'Number')),
                ('transition_state', models.CharField(choices=[(b'NOT_INVOICED', b'Not Invoiced'), (b'RECEIVED', b'Received'), (b'INVOICED', b'Invoiced')], max_length=15, verbose_name=b'Transition State')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract', verbose_name=b'Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.incomeph',),
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.AddField(
            model_name='incomeph',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.BusinessUnit', verbose_name=b'Business Unit'),
        ),
    ]
