# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20160927_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='date_for',
            field=models.DateField(default=datetime.datetime(2016, 9, 27, 22, 12, 20, 733520), verbose_name=b'Date For'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_for',
            field=models.DateField(default=datetime.datetime(2016, 9, 27, 22, 12, 20, 739691), verbose_name=b'Date For'),
        ),
    ]
