# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20160302_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('transation_state', models.CharField(choices=[(b'NOT_INVOICED', b'not invoiced'), (b'RECIEVED', b'recieved'), (b'INVOICED', b'invoiced')], max_length=15)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Contract')),
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Income')),
            ],
        ),
    ]
