# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20160927_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='date_for',
            field=models.DateField(default=None, null=True, verbose_name=b'Date For'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date_for',
            field=models.DateField(default=None, null=True, verbose_name=b'Date For'),
        ),
    ]
