# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Expense')),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Month')),
            ],
        ),
    ]
