# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
