# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_rename_placeholders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoicePH',
            new_name='Invoice',
        ),
    ]
