# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_fiscalyear_cash_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalyear',
            old_name='start_month',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='number_of_months',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
