# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20160406_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='transation_state',
            new_name='transition_state',
        ),
    ]
