# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_auto_20160418_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='data_payable',
            new_name='date_payable',
        ),
    ]
