# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_auto_20160418_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
