# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_auto_20160420_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.CharField(default=b'CSC', max_length=4),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(),
        ),
    ]
