# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20160422_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(),
        ),
    ]
