# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20160427_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Income'),
        ),
    ]
