# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20160428_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='income',
        ),
        migrations.AddField(
            model_name='invoice',
            name='income_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.Income'),
            preserve_default=False,
        ),
    ]
